use myDB;
create table Cities(ID int primary key,City_Name varchar(40));
insert into Cities values(1,'Nagpur');

insert into Cities values(2,'Mumbai');
insert into Cities values(3,'Pune');
insert into Cities values(4,'Thane');
insert into Cities values(5,'Pimpri-Chinchwad');
insert into Cities values(6,'Nashik');
insert into Cities values(7,'Kalyan-dombivli');
insert into Cities values(8,'Vasai-virar');
insert into Cities values(9,'Aurangabad');
insert into Cities values(10,'Navi Mumbai');
insert into Cities values(11,'Solapur');
insert into Cities values(12,'Mira-Bhayandar');
insert into Cities values(13,'Nizmpur');
insert into Cities values(14,'Amravati');
insert into Cities values(15,'Nanded');
insert into Cities values(16,'Kolhapur');
insert into Cities values(17,'Ulhasnager');
insert into Cities values(18,'Kupwad');
insert into Cities values(19,'Malegaon');
insert into Cities values(20,'Jalgaon');
insert into Cities values(21,'Akola');
insert into Cities values(22,'Latur');
insert into Cities values(23,'Dhule');
insert into Cities values(24,'Ahmednager');
insert into Cities values(25,'Chandrpur');
insert into Cities values(26,'Parbhani');
insert into Cities values(27,'Ichalkaranji');
insert into Cities values(28,'Jalna');
insert into Cities values(29,'Ambarnath');
insert into Cities values(30,'Bhusawal');
insert into Cities values(31,'Panvel');
insert into Cities values(32,'Badlapur');
insert into Cities values(33,'Beed');
insert into Cities values(34,'Gondia');
insert into Cities values(35,'Satara');
insert into Cities values(36,'Barshi');
insert into Cities values(37,'Yavatmal');
insert into Cities values(38,'Achalpur');
insert into Cities values(39,'Osmanbad');
insert into Cities values(40,'Wardha');
insert into Cities values(41,'Udgir');
insert into Cities values(42,'Hinganghat');
select * from Cities;