use myDB_Sql;
create table FoodCatergories(ID int primary Key,Category varchar(40));
insert into FoodCatergories values(1,'');
insert into FoodCatergories values(2,'');
insert into FoodCatergories values(3,'');
insert into FoodCatergories values(4,'');
insert into FoodCatergories values(5,'');
insert into FoodCatergories values(6,'');
insert into FoodCatergories values(7,'');
insert into FoodCatergories values(8,'');
insert into FoodCatergories values(9,'');
insert into FoodCatergories values(10,'');
insert into FoodCatergories values(11,'');
insert into FoodCatergories values(12,'');
insert into FoodCatergories values(13,'');
insert into FoodCatergories values(14,'');
insert into FoodCatergories values(15,'');
insert into FoodCatergories values(16,'');
insert into FoodCatergories values(17,'');
insert into FoodCatergories values(18,'');
insert into FoodCatergories values(19,'');
insert into FoodCatergories values(20,'');
Select * from FoodCatergories;